// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://lfnzfencdkkgzaibqutm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmbnpmZW5jZGtrZ3phaWJxdXRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyMDI3MDMsImV4cCI6MjA3NTc3ODcwM30.zWSu74vsGCoBUo3r4FgZGkmvLsVl8Eat3fqy3ufqEgo";

console.log("[Stayzy] Supabase URL present:", !!SUPABASE_URL);
console.log("[Stayzy] Supabase Key present:", !!SUPABASE_PUBLISHABLE_KEY);

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});